// French UI phrase -> English. Used by `tr()` from @/lib/i18n.
// Only UI chrome is translated here; database content (lessons, questions,
// module/course names) is never translated.
export const EN_PHRASES: Record<string, string> = {
  " Les sous-questions seront également supprimées.": " Sub-questions will be deleted as well.",
  "(ou .html) ici, ou cliquez pour parcourir.": "(or .html) here, or click to browse.",
  "(question introuvable)": "(question not found)",
  "(sans nom)": "(untitled)",
  "+1 an": "+1 year",
  "+1 mois": "+1 month",
  "500 dernières actions": "Last 500 actions",
  "Abonnements actuels": "Current subscriptions",
  "Accorder": "Grant",
  "Accorder un abonnement à": "Grant a subscription to",
  "Accès": "Access",
  "Accès & abonnements": "Access & subscriptions",
  "Accès accordé": "Access granted",
  "Accès admin requis": "Admin access required",
  "Accès total. Les permissions ne s'appliquent pas.": "Full access. Permissions do not apply.",
  "Acteur ID:": "Actor ID:",
  "Actif": "Active",
  "Action irréversible.": "This action cannot be undone.",
  "Actualiser": "Refresh",
  "Admin": "Admin",
  "Admin révoqué": "Admin revoked",
  "Administrateurs": "Administrators",
  "Administration": "Administration",
  "Admins": "Admins",
  "Admins existants": "Existing admins",
  "Ajouter aux flashcards": "Add to flashcards",
  "Ajouter un module": "Add a module",
  "Ajouter une permission…": "Add a permission…",
  "Ajoutez au moins un fichier": "Add at least one file",
  "Ajouté aux flashcards": "Added to flashcards",
  "Ambigu": "Ambiguous",
  "Analyse en cours": "Analyzing",
  "Analyser le JSON": "Parse JSON",
  "Analyse…": "Analyzing…",
  "Annuler": "Cancel",
  "Année": "Year",
  "Années d'examen": "Exam years",
  "Années débloquées": "Unlocked years",
  "Appliquer à toutes les lignes": "Apply to all rows",
  "Approuver": "Approve",
  "Approuvée": "Approved",
  "Approuvées": "Approved",
  "Aucun abonnement.": "No subscription.",
  "Aucun admin n'existe encore. Vous pouvez réclamer ce rôle.": "No admin exists yet. You can claim this role.",
  "Aucun admin.": "No admin.",
  "Aucun cours ne correspond.": "No matching course.",
  "Aucun cours pour ce module.": "No course in this module.",
  "Aucun fichier à analyser": "No file to analyze",
  "Aucun module accessible.": "No accessible module.",
  "Aucun module pour l'année {n} pour le moment.": "No module for year {n} yet.",
  "Aucun module.": "No module.",
  "Aucun utilisateur.": "No user.",
  "Aucune année accessible.": "No accessible year.",
  "Aucune demande.": "No request.",
  "Aucune entrée.": "No entry.",
  "Aucune image dans ce contenu.": "No image in this content.",
  "Aucune permission": "No permission",
  "Aucune question détectée": "No question detected",
  "Aucune question manquante pour ce fichier": "No missing question for this file",
  "Aucune question supplémentaire trouvée": "No additional question found",
  "Audit": "Audit",
  "Autre": "Other",
  "BaridiMob (Edahabia)": "BaridiMob (Edahabia)",
  "Barré": "Strikethrough",
  "Bénéficiaire": "Beneficiary",
  "Cas clinique": "Clinical case",
  "Le JSON contient un cas clinique : un énoncé commun est créé et toutes les questions deviennent ses sous-questions.": "The JSON contains a clinical case: a shared vignette is created and every question becomes one of its sub-questions.",
  "Cet abonnement n'expirera jamais.": "This subscription will never expire.",
  "Cette section est réservée aux administrateurs.": "This section is reserved for administrators.",
  "Changer le mot de passe": "Change password",
  "Choisissez d'abord une année d'étude.": "Choose a year of study first.",
  "Choisissez un nouveau mot de passe": "Choose a new password",
  "Chronomètre strict, évaluation à la fin de la session.": "Strict timer, grading at the end of the session.",
  "Cible:": "Target:",
  "Clair": "Light",
  "Cochez les BONNES réponses": "Check the CORRECT answers",
  "Cochez les MAUVAISES réponses": "Check the WRONG answers",
  "Colle la liste des cours (un par ligne) ou importe le programme (PDF, Word, image). Les cours seront créés comme dossiers dans «": "Paste the course list (one per line) or import the syllabus (PDF, Word, image). Courses will be created as folders in \u00ab",
  "Coller du JSON": "Paste JSON",
  "Collez d'abord du JSON.": "Paste some JSON first.",
  "Collé": "Pasted",
  "Compte créé — vous pouvez vous connecter.": "Account created — you can sign in.",
  "Confirmer": "Confirm",
  "Confirmer le mot de passe": "Confirm password",
  "Contenu verrouillé": "Content locked",
  "Continuez votre préparation": "Keep up your prep",
  "Correction": "Feedback",
  "Correction et explications affichées immédiatement.": "Feedback and explanations shown immediately.",
  "Corriger avec l'IA": "Fix with AI",
  "Corrigé": "Fixed",
  "Couleur personnalisée": "Custom color",
  "Cours / TD": "Course / TD",
  "Cours seuls": "Courses only",
  "Créer": "Create",
  "Créé": "Created",
  "Dashboard": "Dashboard",
  "Date d'expiration": "Expiry date",
  "Date fixe": "Fixed date",
  "Demande approuvée": "Request approved",
  "Demande rejetée": "Request rejected",
  "Demandes": "Requests",
  "Descendre": "Move down",
  "Devenir admin": "Become admin",
  "Devise": "Currency",
  "Dossier": "Folder",
  "Défaut": "Default",
  "Déposez les fichiers ici": "Drop the files here",
  "Détails (optionnel)": "Details (optional)",
  "Effacer": "Clear",
  "Effacer la couleur": "Clear color",
  "Email de réinitialisation envoyé": "Reset email sent",
  "Email inconnu": "Unknown email",
  "Email requis": "Email required",
  "En attente": "Pending",
  "En promo": "On sale",
  "Enregistrement…": "Saving…",
  "Enregistrer": "Save",
  "Enregistré": "Saved",
  "Entrez votre email d'abord": "Enter your email first",
  "Envoyer": "Send",
  "Erreur": "Error",
  "Erreur IA": "AI error",
  "Erreur d'analyse": "Parsing error",
  "Erreur d'import": "Import error",
  "Erreur de correction": "Correction error",
  "Erreur médicale": "Medical error",
  "Erreurs": "Errors",
  "Expiration": "Expiry",
  "Expiration mise à jour": "Expiry updated",
  "Expire le ": "Expires on ",
  "Expiré le ": "Expired on ",
  "Explication IA": "AI explanation",
  "Expliquer": "Explain",
  "Externat P1": "Externship P1",
  "Externat P2": "Externship P2",
  "Externat P3": "Externship P3",
  "Extraction 100 % exacte, sans IA ni crédit. Les explications par proposition": "100% exact extraction, no AI and no credits. Per-option explanations",
  "Faute de frappe": "Typo",
  "Faux": "False",
  "Favoris": "Bookmarks",
  "Fichier d'entrée": "Input file",
  "Fichier d'entrée requis": "Input file required",
  "Fichier vide ou illisible": "Empty or unreadable file",
  "Fichiers (plusieurs autorisés)": "Files (multiple allowed)",
  "Filtrer (email, action, cible…)": "Filter (email, action, target…)",
  "Filtrer (nom, référence, méthode…)": "Filter (name, reference, method…)",
  "Filtrer les modules (ex. Cardiologie, Neurologie)…": "Filter modules (e.g. Cardiology, Neurology)…",
  "Flag": "Flag",
  "Format non supporté": "Unsupported format",
  "Formats autorisés": "Allowed formats",
  "Formule": "Plan",
  "Glissez des fichiers": "Drag files",
  "Glissez-déposez ou cliquez pour choisir": "Drag and drop or click to choose",
  "Gras": "Bold",
  "Générateur d'examen global": "Global exam builder",
  "Historique": "History",
  "IA disponible": "AI available",
  "IA indisponible": "AI unavailable",
  "Ignorés :": "Skipped:",
  "Import terminé ({n})": "Import complete ({n})",
  "Importer": "Import",
  "Importer des QCM (images, PDF, Word, Markdown, TXT, JSON)": "Import MCQs (images, PDF, Word, Markdown, TXT, JSON)",
  "Importer des cours HTML (ZIP)": "Import HTML courses (ZIP)",
  "Import…": "Importing…",
  "Inactif": "Inactive",
  "Info supplémentaire": "Extra info",
  "Insert failed": "Insert failed",
  "Instructions": "Instructions",
  "Insérer une image": "Insert an image",
  "Italique": "Italic",
  "JSON invalide": "Invalid JSON",
  "Jamais vues": "Never seen",
  "Journal d'audit": "Audit log",
  "Juste": "Correct",
  "Lancer la session": "Start the session",
  "Les archives multi-fichiers (index.html + assets + sous-pages) sont extraites et servies via un lien signé.": "Multi-file archives (index.html + assets + sub-pages) are extracted and served through a signed link.",
  "Les deux": "Both",
  "Les mots de passe ne correspondent pas": "Passwords do not match",
  "Libellé": "Label",
  "Libellé et numéro requis": "Label and number required",
  "Lisez le cas puis passez à la suite pour répondre aux questions.": "Read the case, then continue to answer the questions.",
  "Liste": "Bullet list",
  "Liste numérotée": "Numbered list",
  "Marquer résolu": "Mark resolved",
  "Mes paiements récents": "My recent payments",
  "Mettre à jour": "Update",
  "Mettre à jour le mot de passe": "Update password",
  "Mis à jour": "Updated",
  "Mise à jour...": "Updating...",
  "Mode entraînement": "Training mode",
  "Mode sans IA : ce PDF n'a pas de couche texte lisible (scan). Décochez le mode sans IA ou importez un fichier Word.": "AI-free mode: this PDF has no readable text layer (scan). Uncheck AI-free mode or import a Word file.",
  "Mode sans IA : les images ne peuvent pas être analysées localement.": "AI-free mode: images cannot be analyzed locally.",
  "Modifier l'expiration": "Edit expiry",
  "Module": "Module",
  "Module requis": "Module required",
  "Modules": "Modules",
  "Monter": "Move up",
  "Mot de passe mis à jour": "Password updated",
  "Mot de passe oublié\u00a0?": "Forgot password?",
  "Mot de passe: 6 caractères minimum": "Password: 6 characters minimum",
  "Motif": "Reason",
  "Motif du rejet ?": "Rejection reason?",
  "Mélanger l'ordre des questions": "Shuffle question order",
  "Méthodes de paiement": "Payment methods",
  "Ne pas changer": "Do not change",
  "Nom, e-mail, id…": "Name, email, id…",
  "Nombre de questions visé": "Target question count",
  "Non spécifiée": "Not specified",
  "Note": "Note",
  "Note personnelle": "Personal note",
  "Nouveau": "New",
  "Nouveau mot de passe": "New password",
  "Nouvelle méthode": "New method",
  "Nouvelle session": "New session",
  "N° de compte": "Account number",
  "Obsolète": "Outdated",
  "Ordre": "Order",
  "Ouverts": "Open",
  "Ouvrez le lien reçu par email pour continuer.": "Open the link you received by email to continue.",
  "PNG, JPG, WebP, GIF, PDF, Word (.docx), Markdown (.md), texte (.txt) ou JSON (.json — extraction exacte, 0 crédit) — plusieurs fichiers à la fois": "PNG, JPG, WebP, GIF, PDF, Word (.docx), Markdown (.md), text (.txt) or JSON (.json — exact extraction, 0 credits) — several files at once",
  "Pack complet": "Full pack",
  "Pack complet (6 années)": "Full pack (6 years)",
  "Pack enregistré": "Pack saved",
  "Paiements": "Payments",
  "Permission requise : gestion des paiements.": "Permission required: payment management.",
  "Permission requise : gestion des tarifs.": "Permission required: pricing management.",
  "Permissions mises à jour": "Permissions updated",
  "Pool de questions filtré": "Filtered question pool",
  "Prix": "Price",
  "Prix par année": "Price per year",
  "Prix promo": "Sale price",
  "Protocole de simulation": "Simulation setup",
  "Précédent": "Previous",
  "Préparation impossible": "Preparation failed",
  "Prêt": "Ready",
  "Questions marquées": "Flagged questions",
  "RIB bancaire": "Bank account (RIB)",
  "Rechercher un cours dans les modules sélectionnés…": "Search a course in the selected modules…",
  "Rechercher un cours…": "Search a course…",
  "Rechercher un module ou une session…": "Search a module or a session…",
  "Refaire les ratées": "Redo the missed ones",
  "Rejeter": "Reject",
  "Rejetée": "Rejected",
  "Rejetées": "Rejected",
  "Rendu tel qu'il sera affiché après enregistrement (liens de stockage re-signés).": "Rendered as it will appear after saving (storage links re-signed).",
  "Reprendre": "Resume",
  "Retirer": "Remove",
  "Retirer cet accès ?": "Remove this access?",
  "Retirer le surlignage": "Remove highlight",
  "Retirer les droits admin de": "Revoke admin rights from",
  "Retiré": "Removed",
  "Retour": "Back",
  "Rien à afficher.": "Nothing to show.",
  "Rien à importer": "Nothing to import",
  "Réf": "Ref",
  "Référence": "Reference",
  "Réinitialiser": "Reset",
  "Réponse attendue :": "Expected answer:",
  "Réponse attendue : ": "Expected answer: ",
  "Répétition espacée": "Spaced repetition",
  "Réservé au super admin": "Super admin only",
  "Réservé au super administrateur.": "Super administrator only.",
  "Résidanat": "Residency",
  "Résolus": "Resolved",
  "Révoquer": "Revoke",
  "Sans dossier": "Unfiled",
  "Sans expiration": "No expiry",
  "Sauvegarde automatique à la sortie du champ.": "Auto-saved when leaving the field.",
  "Score : ": "Score: ",
  "Session": "Session",
  "Session reprise à la question {n}/{total}": "Session resumed at question {n}/{total}",
  "Sessions": "Sessions",
  "Sessions seules": "Sessions only",
  "Seul le super administrateur peut consulter le journal d'audit.": "Only the super administrator can view the audit log.",
  "Seul le super administrateur peut promouvoir d'autres admins.": "Only the super administrator can promote other admins.",
  "Signalement envoyé": "Report sent",
  "Signalements": "Reports",
  "Signalements de questions": "Question reports",
  "Signaler la question": "Report the question",
  "Simulation d'examen": "Exam simulation",
  "Sombre": "Dark",
  "Souligné": "Underline",
  "Source d'examen": "Exam source",
  "Suivant": "Next",
  "Super admin": "Super admin",
  "Supprimer": "Delete",
  "Supprimer ?": "Delete?",
  "Supprimer cette méthode ?": "Delete this method?",
  "Supprimer cette question ?": "Delete this question?",
  "Supprimé": "Deleted",
  "Surligner": "Highlight",
  "Système": "System",
  "Sélectionner cette question": "Select this question",
  "Sélectionner l'année d'étude": "Select the year of study",
  "Sélectionner les cours (Cours / TD)": "Select courses (Course / TD)",
  "Sélectionner les modules": "Select modules",
  "Sélectionner tout": "Select all",
  "Sélectionnez au moins un module": "Select at least one module",
  "Sélectionnez un module ou créez-en un.": "Select a module or create one.",
  "Sélectionnez un module pour voir ses cours. Sans sélection, tous les cours sont inclus.": "Select a module to see its courses. With no selection, all courses are included.",
  "Sélectionnez un utilisateur.": "Select a user.",
  "TD": "TD",
  "Tableau de bord": "Dashboard",
  "Tarifs": "Pricing",
  "Temps écoulé — session terminée": "Time is up — session finished",
  "Terminer": "Finish",
  "Terminé": "Finished",
  "Test d'aperçu des images": "Image preview test",
  "Test en cours…": "Testing…",
  "Test impossible": "Test failed",
  "Tester l'IA": "Test the AI",
  "Tester l'aperçu des images": "Test image preview",
  "Texte": "Text",
  "Thème": "Theme",
  "Titre": "Title",
  "Titre requis": "Title required",
  "Total encaissé": "Total collected",
  "Tous": "All",
  "Tout désélectionner": "Deselect all",
  "Tout effacer": "Clear all",
  "Tout importer": "Import all",
  "Tout sélectionner": "Select all",
  "Toutes": "All",
  "Toutes les années": "All years",
  "Toutes les sources": "All sources",
  "Type": "Type",
  "Types de questions & données d'examen": "Question types & exam data",
  "Un admin existe déjà": "An admin already exists",
  "Une année": "One year",
  "Upload": "Upload",
  "Utilisateurs": "Users",
  "Valeur déjà assignée": "Value already assigned",
  "Valeurs par défaut (appliquées aux nouvelles lignes)": "Default values (applied to new rows)",
  "Valider": "Submit",
  "Verrouillé": "Locked",
  "Vider": "Clear",
  "Voir la boutique": "Open store",
  "Voir la preuve": "View proof",
  "Voir tout": "View all",
  "Vos modules": "Your modules",
  "Vos remarques sur cette question…": "Your remarks about this question…",
  "Votre formule ne comprend pas les cours. Ajoutez la formule « Cours » ou « Les deux » pour y accéder.": "Your plan does not include courses. Add the \u00ab Courses \u00bb or \u00ab Both \u00bb plan to access them.",
  "Votre formule ne comprend pas les sessions de questions. Ajoutez la formule « Sessions » ou « Les deux » pour y accéder.": "Your plan does not include question sessions. Add the \u00ab Sessions \u00bb or \u00ab Both \u00bb plan to access them.",
  "Votre réponse :": "Your answer:",
  "Votre réponse…": "Your answer…",
  "Vous n'avez encore accès à aucune année.": "You do not have access to any year yet.",
  "Vous êtes admin": "You are an admin",
  "Vérifie la disponibilité de l'IA intégrée utilisée pour l'extraction.": "Checks availability of the built-in AI used for extraction.",
  "ajoutée": "added",
  "dossier(s) dans «": "folder(s) in \u00ab",
  "détectée(s) — relancez les fichiers incomplets": "detected — re-run the incomplete files",
  "en": "in",
  "enregistrée": "saved",
  "entrée(s)": "entry(ies)",
  "est maintenant admin": "is now an admin",
  "fichier(s)": "file(s)",
  "flashcard": "flashcard",
  "mauvaises réponses": "wrong answers",
  "module": "module",
  "modules": "modules",
  "ou": "or",
  "page(s) sans texte (scan) ignorée(s) par la lecture rapide": "page(s) without text (scan) skipped by the fast reader",
  "q": "q",
  "question prête": "question ready",
  "question(s) détectée(s)": "question(s) detected",
  "question(s) détectée(s) dans le JSON collé.": "question(s) detected in the pasted JSON.",
  "question(s) extraite(s) sur": "question(s) extracted out of",
  "question(s) importée(s)": "question(s) imported",
  "question(s) supplémentaire(s) récupérée(s)": "additional question(s) recovered",
  "questions": "questions",
  "questions prêtes": "questions ready",
  "répondues": "answered",
  "réponse": "answer",
  "signalement": "report",
  "signalements": "reports",
  "sont importées ligne par ligne.": "are imported line by line.",
  "sous-question(s)": "sub-question(s)",
  "système": "system",
  "{n} image(s) OK": "{n} image(s) OK",
  "{n} image(s) ne se chargent pas": "{n} image(s) failed to load",
  "À réviser": "To review",
  "Échec Google": "Google sign-in failed",
  "Écrivez votre réponse": "Write your answer",
  "à cocher": "to check",
  "ème année": "th year",
  "ᵉ année": "th year",
  "— aucune année —": "— no year —",
  "— aucune rotation —": "— no rotation —",
  "≤": "≤",
  "≥": "≥",
  "✓ Bonne réponse": "✓ Correct answer",
  "✗ Mauvaise réponse": "✗ Wrong answer",
  "Énoncé": "Case brief",
  "Voir les réponses": "Show answers",
  "Répondu": "Answered",
  "Question": "Question",
};
