/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedStoreRouteImport } from './routes/_authenticated/store'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminAccessRouteImport } from './routes/_authenticated/admin.access'
import { Route as AuthenticatedAdminAdminsRouteImport } from './routes/_authenticated/admin.admins'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin.audit'
import { Route as AuthenticatedAdminConvertRouteImport } from './routes/_authenticated/admin.convert'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin.payments'
import { Route as AuthenticatedAdminPricingRouteImport } from './routes/_authenticated/admin.pricing'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin.reports'
import { Route as AuthenticatedModulesModuleIdRouteImport } from './routes/_authenticated/modules.$moduleId'
import { Route as AuthenticatedQuestionsIndexRouteImport } from './routes/_authenticated/questions.index'
import { Route as AuthenticatedQuestionsFlashcardsRouteImport } from './routes/_authenticated/questions.flashcards'
import { Route as AuthenticatedQuestionsHistoryRouteImport } from './routes/_authenticated/questions.history'
import { Route as AuthenticatedQuestionsNewRouteImport } from './routes/_authenticated/questions.new'
import { Route as AuthenticatedQuestionsStatsRouteImport } from './routes/_authenticated/questions.stats'
import { Route as AuthenticatedModulesModuleIdIndexRouteImport } from './routes/_authenticated/modules.$moduleId.index'
import { Route as AuthenticatedModulesModuleIdContentIdRouteImport } from './routes/_authenticated/modules.$moduleId.$contentId'
import { Route as AuthenticatedModulesModuleIdCasCliniquesRouteImport } from './routes/_authenticated/modules.$moduleId.cas-cliniques'
import { Route as AuthenticatedModulesModuleIdCoursRouteImport } from './routes/_authenticated/modules.$moduleId.cours'
import { Route as AuthenticatedModulesModuleIdEntrainementRouteImport } from './routes/_authenticated/modules.$moduleId.entrainement'
import { Route as ApiMfTokenSplatRouteImport } from './routes/api/mf.$token.$'
import { Route as AuthenticatedModulesModuleIdFoldersFolderIdRouteImport } from './routes/_authenticated/modules.$moduleId.folders.$folderId'
import { Route as AuthenticatedModulesModuleIdQcmSessionIdRouteImport } from './routes/_authenticated/modules.$moduleId.qcm.$sessionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStoreRoute = AuthenticatedStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminAccessRoute =
  AuthenticatedAdminAccessRouteImport.update({
    id: '/admin/access',
    path: '/admin/access',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAdminsRoute =
  AuthenticatedAdminAdminsRouteImport.update({
    id: '/admin/admins',
    path: '/admin/admins',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminConvertRoute =
  AuthenticatedAdminConvertRouteImport.update({
    id: '/admin/convert',
    path: '/admin/convert',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/admin/payments',
    path: '/admin/payments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPricingRoute =
  AuthenticatedAdminPricingRouteImport.update({
    id: '/admin/pricing',
    path: '/admin/pricing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/admin/reports',
    path: '/admin/reports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedModulesModuleIdRoute =
  AuthenticatedModulesModuleIdRouteImport.update({
    id: '/modules/$moduleId',
    path: '/modules/$moduleId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQuestionsIndexRoute =
  AuthenticatedQuestionsIndexRouteImport.update({
    id: '/questions/',
    path: '/questions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQuestionsFlashcardsRoute =
  AuthenticatedQuestionsFlashcardsRouteImport.update({
    id: '/questions/flashcards',
    path: '/questions/flashcards',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQuestionsHistoryRoute =
  AuthenticatedQuestionsHistoryRouteImport.update({
    id: '/questions/history',
    path: '/questions/history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQuestionsNewRoute =
  AuthenticatedQuestionsNewRouteImport.update({
    id: '/questions/new',
    path: '/questions/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQuestionsStatsRoute =
  AuthenticatedQuestionsStatsRouteImport.update({
    id: '/questions/stats',
    path: '/questions/stats',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedModulesModuleIdIndexRoute =
  AuthenticatedModulesModuleIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedModulesModuleIdRoute,
  } as any)
const AuthenticatedModulesModuleIdContentIdRoute =
  AuthenticatedModulesModuleIdContentIdRouteImport.update({
    id: '/$contentId',
    path: '/$contentId',
    getParentRoute: () => AuthenticatedModulesModuleIdRoute,
  } as any)
const AuthenticatedModulesModuleIdCasCliniquesRoute =
  AuthenticatedModulesModuleIdCasCliniquesRouteImport.update({
    id: '/cas-cliniques',
    path: '/cas-cliniques',
    getParentRoute: () => AuthenticatedModulesModuleIdRoute,
  } as any)
const AuthenticatedModulesModuleIdCoursRoute =
  AuthenticatedModulesModuleIdCoursRouteImport.update({
    id: '/cours',
    path: '/cours',
    getParentRoute: () => AuthenticatedModulesModuleIdRoute,
  } as any)
const AuthenticatedModulesModuleIdEntrainementRoute =
  AuthenticatedModulesModuleIdEntrainementRouteImport.update({
    id: '/entrainement',
    path: '/entrainement',
    getParentRoute: () => AuthenticatedModulesModuleIdRoute,
  } as any)
const ApiMfTokenSplatRoute = ApiMfTokenSplatRouteImport.update({
  id: '/api/mf/$token/$',
  path: '/api/mf/$token/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedModulesModuleIdFoldersFolderIdRoute =
  AuthenticatedModulesModuleIdFoldersFolderIdRouteImport.update({
    id: '/folders/$folderId',
    path: '/folders/$folderId',
    getParentRoute: () => AuthenticatedModulesModuleIdRoute,
  } as any)
const AuthenticatedModulesModuleIdQcmSessionIdRoute =
  AuthenticatedModulesModuleIdQcmSessionIdRouteImport.update({
    id: '/qcm/$sessionId',
    path: '/qcm/$sessionId',
    getParentRoute: () => AuthenticatedModulesModuleIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/store': typeof AuthenticatedStoreRoute
  '/admin/access': typeof AuthenticatedAdminAccessRoute
  '/admin/admins': typeof AuthenticatedAdminAdminsRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/convert': typeof AuthenticatedAdminConvertRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/pricing': typeof AuthenticatedAdminPricingRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/modules/$moduleId': typeof AuthenticatedModulesModuleIdRouteWithChildren
  '/questions/flashcards': typeof AuthenticatedQuestionsFlashcardsRoute
  '/questions/history': typeof AuthenticatedQuestionsHistoryRoute
  '/questions/new': typeof AuthenticatedQuestionsNewRoute
  '/questions/stats': typeof AuthenticatedQuestionsStatsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/questions/': typeof AuthenticatedQuestionsIndexRoute
  '/modules/$moduleId/$contentId': typeof AuthenticatedModulesModuleIdContentIdRoute
  '/modules/$moduleId/cas-cliniques': typeof AuthenticatedModulesModuleIdCasCliniquesRoute
  '/modules/$moduleId/cours': typeof AuthenticatedModulesModuleIdCoursRoute
  '/modules/$moduleId/entrainement': typeof AuthenticatedModulesModuleIdEntrainementRoute
  '/api/mf/$token/$': typeof ApiMfTokenSplatRoute
  '/modules/$moduleId/': typeof AuthenticatedModulesModuleIdIndexRoute
  '/modules/$moduleId/folders/$folderId': typeof AuthenticatedModulesModuleIdFoldersFolderIdRoute
  '/modules/$moduleId/qcm/$sessionId': typeof AuthenticatedModulesModuleIdQcmSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/store': typeof AuthenticatedStoreRoute
  '/admin/access': typeof AuthenticatedAdminAccessRoute
  '/admin/admins': typeof AuthenticatedAdminAdminsRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/convert': typeof AuthenticatedAdminConvertRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/pricing': typeof AuthenticatedAdminPricingRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/questions/flashcards': typeof AuthenticatedQuestionsFlashcardsRoute
  '/questions/history': typeof AuthenticatedQuestionsHistoryRoute
  '/questions/new': typeof AuthenticatedQuestionsNewRoute
  '/questions/stats': typeof AuthenticatedQuestionsStatsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/questions': typeof AuthenticatedQuestionsIndexRoute
  '/modules/$moduleId/$contentId': typeof AuthenticatedModulesModuleIdContentIdRoute
  '/modules/$moduleId/cas-cliniques': typeof AuthenticatedModulesModuleIdCasCliniquesRoute
  '/modules/$moduleId/cours': typeof AuthenticatedModulesModuleIdCoursRoute
  '/modules/$moduleId/entrainement': typeof AuthenticatedModulesModuleIdEntrainementRoute
  '/api/mf/$token/$': typeof ApiMfTokenSplatRoute
  '/modules/$moduleId': typeof AuthenticatedModulesModuleIdIndexRoute
  '/modules/$moduleId/folders/$folderId': typeof AuthenticatedModulesModuleIdFoldersFolderIdRoute
  '/modules/$moduleId/qcm/$sessionId': typeof AuthenticatedModulesModuleIdQcmSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/store': typeof AuthenticatedStoreRoute
  '/_authenticated/admin/access': typeof AuthenticatedAdminAccessRoute
  '/_authenticated/admin/admins': typeof AuthenticatedAdminAdminsRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/convert': typeof AuthenticatedAdminConvertRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin/pricing': typeof AuthenticatedAdminPricingRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/modules/$moduleId': typeof AuthenticatedModulesModuleIdRouteWithChildren
  '/_authenticated/questions/flashcards': typeof AuthenticatedQuestionsFlashcardsRoute
  '/_authenticated/questions/history': typeof AuthenticatedQuestionsHistoryRoute
  '/_authenticated/questions/new': typeof AuthenticatedQuestionsNewRoute
  '/_authenticated/questions/stats': typeof AuthenticatedQuestionsStatsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/questions/': typeof AuthenticatedQuestionsIndexRoute
  '/_authenticated/modules/$moduleId/$contentId': typeof AuthenticatedModulesModuleIdContentIdRoute
  '/_authenticated/modules/$moduleId/cas-cliniques': typeof AuthenticatedModulesModuleIdCasCliniquesRoute
  '/_authenticated/modules/$moduleId/cours': typeof AuthenticatedModulesModuleIdCoursRoute
  '/_authenticated/modules/$moduleId/entrainement': typeof AuthenticatedModulesModuleIdEntrainementRoute
  '/api/mf/$token/$': typeof ApiMfTokenSplatRoute
  '/_authenticated/modules/$moduleId/': typeof AuthenticatedModulesModuleIdIndexRoute
  '/_authenticated/modules/$moduleId/folders/$folderId': typeof AuthenticatedModulesModuleIdFoldersFolderIdRoute
  '/_authenticated/modules/$moduleId/qcm/$sessionId': typeof AuthenticatedModulesModuleIdQcmSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/dashboard'
    | '/profile'
    | '/store'
    | '/admin/access'
    | '/admin/admins'
    | '/admin/audit'
    | '/admin/convert'
    | '/admin/payments'
    | '/admin/pricing'
    | '/admin/reports'
    | '/modules/$moduleId'
    | '/questions/flashcards'
    | '/questions/history'
    | '/questions/new'
    | '/questions/stats'
    | '/admin/'
    | '/questions/'
    | '/modules/$moduleId/$contentId'
    | '/modules/$moduleId/cas-cliniques'
    | '/modules/$moduleId/cours'
    | '/modules/$moduleId/entrainement'
    | '/api/mf/$token/$'
    | '/modules/$moduleId/'
    | '/modules/$moduleId/folders/$folderId'
    | '/modules/$moduleId/qcm/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/dashboard'
    | '/profile'
    | '/store'
    | '/admin/access'
    | '/admin/admins'
    | '/admin/audit'
    | '/admin/convert'
    | '/admin/payments'
    | '/admin/pricing'
    | '/admin/reports'
    | '/questions/flashcards'
    | '/questions/history'
    | '/questions/new'
    | '/questions/stats'
    | '/admin'
    | '/questions'
    | '/modules/$moduleId/$contentId'
    | '/modules/$moduleId/cas-cliniques'
    | '/modules/$moduleId/cours'
    | '/modules/$moduleId/entrainement'
    | '/api/mf/$token/$'
    | '/modules/$moduleId'
    | '/modules/$moduleId/folders/$folderId'
    | '/modules/$moduleId/qcm/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/_authenticated/dashboard'
    | '/_authenticated/profile'
    | '/_authenticated/store'
    | '/_authenticated/admin/access'
    | '/_authenticated/admin/admins'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/convert'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/pricing'
    | '/_authenticated/admin/reports'
    | '/_authenticated/modules/$moduleId'
    | '/_authenticated/questions/flashcards'
    | '/_authenticated/questions/history'
    | '/_authenticated/questions/new'
    | '/_authenticated/questions/stats'
    | '/_authenticated/admin/'
    | '/_authenticated/questions/'
    | '/_authenticated/modules/$moduleId/$contentId'
    | '/_authenticated/modules/$moduleId/cas-cliniques'
    | '/_authenticated/modules/$moduleId/cours'
    | '/_authenticated/modules/$moduleId/entrainement'
    | '/api/mf/$token/$'
    | '/_authenticated/modules/$moduleId/'
    | '/_authenticated/modules/$moduleId/folders/$folderId'
    | '/_authenticated/modules/$moduleId/qcm/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  ApiMfTokenSplatRoute: typeof ApiMfTokenSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/store': {
      id: '/_authenticated/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof AuthenticatedStoreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/access': {
      id: '/_authenticated/admin/access'
      path: '/admin/access'
      fullPath: '/admin/access'
      preLoaderRoute: typeof AuthenticatedAdminAccessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/admins': {
      id: '/_authenticated/admin/admins'
      path: '/admin/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof AuthenticatedAdminAdminsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/convert': {
      id: '/_authenticated/admin/convert'
      path: '/admin/convert'
      fullPath: '/admin/convert'
      preLoaderRoute: typeof AuthenticatedAdminConvertRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/pricing': {
      id: '/_authenticated/admin/pricing'
      path: '/admin/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AuthenticatedAdminPricingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/modules/$moduleId': {
      id: '/_authenticated/modules/$moduleId'
      path: '/modules/$moduleId'
      fullPath: '/modules/$moduleId'
      preLoaderRoute: typeof AuthenticatedModulesModuleIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/questions/': {
      id: '/_authenticated/questions/'
      path: '/questions'
      fullPath: '/questions/'
      preLoaderRoute: typeof AuthenticatedQuestionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/questions/flashcards': {
      id: '/_authenticated/questions/flashcards'
      path: '/questions/flashcards'
      fullPath: '/questions/flashcards'
      preLoaderRoute: typeof AuthenticatedQuestionsFlashcardsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/questions/history': {
      id: '/_authenticated/questions/history'
      path: '/questions/history'
      fullPath: '/questions/history'
      preLoaderRoute: typeof AuthenticatedQuestionsHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/questions/new': {
      id: '/_authenticated/questions/new'
      path: '/questions/new'
      fullPath: '/questions/new'
      preLoaderRoute: typeof AuthenticatedQuestionsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/questions/stats': {
      id: '/_authenticated/questions/stats'
      path: '/questions/stats'
      fullPath: '/questions/stats'
      preLoaderRoute: typeof AuthenticatedQuestionsStatsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/modules/$moduleId/': {
      id: '/_authenticated/modules/$moduleId/'
      path: '/'
      fullPath: '/modules/$moduleId/'
      preLoaderRoute: typeof AuthenticatedModulesModuleIdIndexRouteImport
      parentRoute: typeof AuthenticatedModulesModuleIdRoute
    }
    '/_authenticated/modules/$moduleId/$contentId': {
      id: '/_authenticated/modules/$moduleId/$contentId'
      path: '/$contentId'
      fullPath: '/modules/$moduleId/$contentId'
      preLoaderRoute: typeof AuthenticatedModulesModuleIdContentIdRouteImport
      parentRoute: typeof AuthenticatedModulesModuleIdRoute
    }
    '/_authenticated/modules/$moduleId/cas-cliniques': {
      id: '/_authenticated/modules/$moduleId/cas-cliniques'
      path: '/cas-cliniques'
      fullPath: '/modules/$moduleId/cas-cliniques'
      preLoaderRoute: typeof AuthenticatedModulesModuleIdCasCliniquesRouteImport
      parentRoute: typeof AuthenticatedModulesModuleIdRoute
    }
    '/_authenticated/modules/$moduleId/cours': {
      id: '/_authenticated/modules/$moduleId/cours'
      path: '/cours'
      fullPath: '/modules/$moduleId/cours'
      preLoaderRoute: typeof AuthenticatedModulesModuleIdCoursRouteImport
      parentRoute: typeof AuthenticatedModulesModuleIdRoute
    }
    '/_authenticated/modules/$moduleId/entrainement': {
      id: '/_authenticated/modules/$moduleId/entrainement'
      path: '/entrainement'
      fullPath: '/modules/$moduleId/entrainement'
      preLoaderRoute: typeof AuthenticatedModulesModuleIdEntrainementRouteImport
      parentRoute: typeof AuthenticatedModulesModuleIdRoute
    }
    '/api/mf/$token/$': {
      id: '/api/mf/$token/$'
      path: '/api/mf/$token/$'
      fullPath: '/api/mf/$token/$'
      preLoaderRoute: typeof ApiMfTokenSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/modules/$moduleId/folders/$folderId': {
      id: '/_authenticated/modules/$moduleId/folders/$folderId'
      path: '/folders/$folderId'
      fullPath: '/modules/$moduleId/folders/$folderId'
      preLoaderRoute: typeof AuthenticatedModulesModuleIdFoldersFolderIdRouteImport
      parentRoute: typeof AuthenticatedModulesModuleIdRoute
    }
    '/_authenticated/modules/$moduleId/qcm/$sessionId': {
      id: '/_authenticated/modules/$moduleId/qcm/$sessionId'
      path: '/qcm/$sessionId'
      fullPath: '/modules/$moduleId/qcm/$sessionId'
      preLoaderRoute: typeof AuthenticatedModulesModuleIdQcmSessionIdRouteImport
      parentRoute: typeof AuthenticatedModulesModuleIdRoute
    }
  }
}

interface AuthenticatedModulesModuleIdRouteChildren {
  AuthenticatedModulesModuleIdContentIdRoute: typeof AuthenticatedModulesModuleIdContentIdRoute
  AuthenticatedModulesModuleIdCasCliniquesRoute: typeof AuthenticatedModulesModuleIdCasCliniquesRoute
  AuthenticatedModulesModuleIdCoursRoute: typeof AuthenticatedModulesModuleIdCoursRoute
  AuthenticatedModulesModuleIdEntrainementRoute: typeof AuthenticatedModulesModuleIdEntrainementRoute
  AuthenticatedModulesModuleIdIndexRoute: typeof AuthenticatedModulesModuleIdIndexRoute
  AuthenticatedModulesModuleIdFoldersFolderIdRoute: typeof AuthenticatedModulesModuleIdFoldersFolderIdRoute
  AuthenticatedModulesModuleIdQcmSessionIdRoute: typeof AuthenticatedModulesModuleIdQcmSessionIdRoute
}

const AuthenticatedModulesModuleIdRouteChildren: AuthenticatedModulesModuleIdRouteChildren =
  {
    AuthenticatedModulesModuleIdContentIdRoute:
      AuthenticatedModulesModuleIdContentIdRoute,
    AuthenticatedModulesModuleIdCasCliniquesRoute:
      AuthenticatedModulesModuleIdCasCliniquesRoute,
    AuthenticatedModulesModuleIdCoursRoute:
      AuthenticatedModulesModuleIdCoursRoute,
    AuthenticatedModulesModuleIdEntrainementRoute:
      AuthenticatedModulesModuleIdEntrainementRoute,
    AuthenticatedModulesModuleIdIndexRoute:
      AuthenticatedModulesModuleIdIndexRoute,
    AuthenticatedModulesModuleIdFoldersFolderIdRoute:
      AuthenticatedModulesModuleIdFoldersFolderIdRoute,
    AuthenticatedModulesModuleIdQcmSessionIdRoute:
      AuthenticatedModulesModuleIdQcmSessionIdRoute,
  }

const AuthenticatedModulesModuleIdRouteWithChildren =
  AuthenticatedModulesModuleIdRoute._addFileChildren(
    AuthenticatedModulesModuleIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedStoreRoute: typeof AuthenticatedStoreRoute
  AuthenticatedAdminAccessRoute: typeof AuthenticatedAdminAccessRoute
  AuthenticatedAdminAdminsRoute: typeof AuthenticatedAdminAdminsRoute
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminConvertRoute: typeof AuthenticatedAdminConvertRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminPricingRoute: typeof AuthenticatedAdminPricingRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedModulesModuleIdRoute: typeof AuthenticatedModulesModuleIdRouteWithChildren
  AuthenticatedQuestionsFlashcardsRoute: typeof AuthenticatedQuestionsFlashcardsRoute
  AuthenticatedQuestionsHistoryRoute: typeof AuthenticatedQuestionsHistoryRoute
  AuthenticatedQuestionsNewRoute: typeof AuthenticatedQuestionsNewRoute
  AuthenticatedQuestionsStatsRoute: typeof AuthenticatedQuestionsStatsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedQuestionsIndexRoute: typeof AuthenticatedQuestionsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedStoreRoute: AuthenticatedStoreRoute,
  AuthenticatedAdminAccessRoute: AuthenticatedAdminAccessRoute,
  AuthenticatedAdminAdminsRoute: AuthenticatedAdminAdminsRoute,
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminConvertRoute: AuthenticatedAdminConvertRoute,
  AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
  AuthenticatedAdminPricingRoute: AuthenticatedAdminPricingRoute,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
  AuthenticatedModulesModuleIdRoute:
    AuthenticatedModulesModuleIdRouteWithChildren,
  AuthenticatedQuestionsFlashcardsRoute: AuthenticatedQuestionsFlashcardsRoute,
  AuthenticatedQuestionsHistoryRoute: AuthenticatedQuestionsHistoryRoute,
  AuthenticatedQuestionsNewRoute: AuthenticatedQuestionsNewRoute,
  AuthenticatedQuestionsStatsRoute: AuthenticatedQuestionsStatsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedQuestionsIndexRoute: AuthenticatedQuestionsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  ApiMfTokenSplatRoute: ApiMfTokenSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
